spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/anime
    username: postgres
    password: admin

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param